version: "3.1"

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MonolithFood12345
      POSTGRES_DB: monolithfooddb
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/monolithfooddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: MonolithFood12345
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"

  angularapp:
    build:
      context: ../MonolithFoodFrontend
      dockerfile: Dockerfile
    depends_on:
      - springbootapp
    ports:
      - "80:80"

volumes:
  postgres:
